### ISSUE TITLE
Missing files (?)

### ISSUE THREAD

**Issue by VirtuaCreative** [rriemann/html5-up-landed-middleman4#1]
Hey there,

I'm trying to use your template, but apparently there are some files missing. You import them to `main.css.scss` but actually they are not there:

```
@import 'font-awesome-sprockets';
@import 'font-awesome';
...
    @import 'skel/dist/_skel';
```

So the layout crashes.

Am I doing something wrong? I'm experienced in Jekyll, but new to Middleman.

I'm serving "mdm" with bundler: `bundle exec middleman server`

**Comment by rriemann** [comment]
I will try to have a look this afternoon or tomorrow. In principle, theses files should be part of some gems and middleman should find them not in the source folder of the template, but in a folder installed by the gem.

**Comment by rriemann** [comment]
Can you please post your `Gemfile.lock`? I cannot reproduce the error.

**Comment by VirtuaCreative** [comment]
Worked. Thanks!

**Comment by VirtuaCreative** [comment]
Accually, the "left-sidebar" layout is displaying two footers. But I removed from the `left-sidebar.html.slim` and it's ok now.
